### ISSUE TITLE
why occured "No XML <RequestPassword> or <RequestToken> was found in XML Request." error when 1.8.7 is ok but  use rvm ruby 1.9.2 is not ?

### ISSUE THREAD

**Issue by kewinwang** [codyfauser/ebay#12]
kewin@office~/ebay_project/ebay/examples>ruby -v
ruby 1.9.2p180 (2011-02-18 revision 30909) [i686-linux]
kewin@office~/ebay_project/ebay/examples>ruby  get_ebay_time.rb 
No XML "RequestPassword" or "RequestToken" was found in XML Request.
kewin@office~/ebay_project/ebay/examples>rvm use system
Now using system ruby.
kewin@office~/ebay_project/ebay/examples>ruby  get_ebay_time.rb 
The returned class is: Ebay::Responses::GeteBayOfficialTime
The current eBay time is: Tue Aug 23 07:58:15 UTC 2011
kewin@office~/ebay_project/ebay/examples>

**Comment by dingzj** [comment]
@kewinwang have you figure this what the reason? 
Trying to use this gem, and none of the call succeed.
